export { apiService } from './api'
export { authService } from './auth'
export { homeService } from './Home'
export { cartService } from './Cart'
export { productService } from './Product'
export { profileService } from './Profile'
export { pagesService } from './Pages'
export { postService } from './Post'
